linters:
  enable:
    - bodyclose
    - decorder
    - dogsled
    - errorlint
    - exhaustive
    - exportloopref
    - exhaustive
    #- gocognit
    - goconst
    #- gocyclo
    - gosec
    - makezero
    #- nestif
    - nilerr
    - prealloc
    - unconvert
    - unparam
    - noctx

issues:
  max-same-issues: 0
